### ISSUE TITLE
Move compiler options out of source code (and onto command line)

### ISSUE THREAD

**Issue by samiam95124** [samiam95124/Pascal-P6#122]
The use of options in the source is compiler specific. Pascal-P6 can parse options from the command line (in extended mode), so does not really need this anymore. The options, in the few places they are required, can be part of the Makefile and in scripts.

**Comment by electric-socket** [comment]
I disagree with this. The ability to put switches in code (*$ or {$ goes back at least 45 years, the [AAEC Pascal 8000](https://github.com/electric-socket/pascal8000) compiler had them in 1977. It's just accepting them from the source instead of only from the command line. I mean, compile-time parameters in code go back a long way to when {$IF/$endif/{$define were implemented for conditional compilation. I suspect it might break things.

**Comment by samiam95124** [comment]
Thanks for the comment.

I suspect there was a misunderstanding here, I wasn't proposing to remove the ability to use options in the source code. #122 was to move the option sets from source code into make files and script files.

Regards,

Scott Franco

**Comment by samiam95124** [comment]
# A PS to this:

Although option comments are indeed an old Pascal convention that even made it over to Borland Pascal, they commonly got changed in meaning. For example, FPC comment characters have different meanings that the original Pascal-P use. This becomes an issue when compiling Pascal-P programs with FPC.

**Comment by samiam95124** [comment]
## What is, and what is not an inline comment

In the original Pascal-P (P1-P5), source comment options were the only way to select an option. Pascal-P6 changed that. Thus it makes sense to go into what options belong in the source, and what options do not.

To me, the rule is simple (you are welcome to your own rule(s)):

1. Options that indicate *characteristics* of the source belong with the source. Examples include $u- (tagfield checking) on Pascal-s, or $d- (debug checks) on pint. Those programs need special setups to compile.
2. Options that indicate *modes* don't really belong with the source. The classic example is $l, or to list the source program or not. Its good to find errors. Its annoying if you are just running a compile.

The way I have refactored the code, it really becomes program dependent. For example, pcom, pint and friends have their options set in the makefile, whereas others do not. The reason why is those programs need special recipes provided in the makefile, so it makes sense that they would also get the options needed for the programs. Other programs go through standardized script files, and so carry their source options. Pascal-S is a good example of that.

**Comment by samiam95124** [comment]
This issue is complete.
